# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="bezoar" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Bezoar" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="bezoar.png" #optional
# A text field displayed in the mod UI
credits="Inspiration for this mod is thanks to both Terraria and BrassGeo> BrassGeo gave me the chance to code my first mod and for that I am grateful" #optional
# A text field displayed in the mod UI
authors="Milamber and BrassGeo" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A small mod that adds Terraria esq Hornets to the minecraft Jungle Biome.

Hornets:
Honey Hornet
-will steal fruits from you 1 at a time when flying into the player [this includes golden apples]

Floral Hornet
-when struck, the hornet has a 1/8 chance to release 2-4 angry bees with speed boost 2

Mossy Hornet
-slowly heals overtime [0.5 hearts every 3 seconds]

Spikey Hornet
-does 2x melee damage

Delta Hornet
-does not poison, with stingers instead doing blaze melee damage
-hit with a snowball to temporarily disable its stinger, but doing no damage [hornet smokes breifly after hit]

Chrorus Hornet
-teleports 2x as often as endermen
-sheds endermites from time to times
-stinger projectiles also inflict levitation for 3 seconds
'''
[[dependencies.bezoar]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
